# H2 DataBase?
spring:
  profiles:
    active: local
  application:
    name: spring-batch-jpa
  datasource:
    hikari:
      maximum-pool-size: 10
  batch:
    job:
      enabled: true
      name: JPA_ITEM_WRITER_JOB #JPA_PAGING_CHUNK_JOB # JPA_ITEM_WRITER_JOB
  sql:
    init:
      mode: never
  config:
    import: classpath:secret.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
